module.exports = Object.freeze({

  NONE: 'UNDEFINED',
  INCOMING: 'INCOMING_PENDING',
  OUTGOING: 'OUTGOING_PENDING',
  ACCEPTED: 'ACCEPTED',
  BLOCKED: 'BLOCKED',
  REMOVED: 'REMOVED',
  REJECTED: 'REJECTED',
  ABORTED: 'ABORTED',

});
